### ISSUE TITLE
Add function to make Plugin re-read source files

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dubmanager#4]
Currently if I add new sources files to my Dub project there is no way to get the dubmanager plugin to reload the list of source files and to refresh the project tree view. For that to work I have to close and reopen the project. In the CMake plugin it is enough to hit the "Run CMake" button in the project's context menu. 

It would be nice to have a project menu option to advise the plugin to reload the Dub configuration. A "Refresh sourcetree" or "Reload configuration" item would be really great.

**Comment by Groterik** [comment]
But this button already exists in Project mode (Ctrl + 5). You can find it near the "Update project" label.

**Comment by stonemaster** [comment]
Thanks! I didn't know it already existed at that place. But the new function is really good. +1
