### ISSUE TITLE
Add wizard to create empty DUB project

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dubmanager#5]
It would be great to be able to create new DUB projects from the IDE. This came up during a discussion in the D forums: http://forum.dlang.org/thread/njfeqjvihpkdbrspnglr@forum.dlang.org?page=3#post-mailman.1337.1428512188.3111.digitalmars-d:40puremagic.com

**Comment by Groterik** [comment]
Yep, this is good idea. I don't have enough time now but I will try to implement it within a week.
Thank you.
